name: Build and Check for Changes
on:
  # This workflow uses the pull_request trigger which prevents write permissions and secrets
  # access to the target repository from public forks.  This should remain as a pull_request
  # trigger because checkout, build, format and checking for changes do not need elevated
  # permissions to the repository.  The reduced permissions for public forks is adequate.
  # Since this will commit readme/recompile changes back to the branch, special attention 
  # should be paid to changes made to this workflow when reviewing the PR and granting 
  # permission to first time contributors to run the workflow.
  pull_request:
  # Don't include any specific paths here so we always get a build that produces a status
  # check that our Branch Protection Rules can use.  Having a status check also allows us
  # to require that branches be up to date before they are merged.

jobs:
  build:
    uses: im-open/.github/.github/workflows/reusable-javascript-build.yml@reusable-updates
    with:
      default-branch: main
      node-version: 16.x
      files-with-code: 'action.yml,package.json,package-lock.json'
      folders-with-code: 'src,dist'
      build-command: 'npm run build'
      readme-location: './README.md'
      action-name: ${{ github.repository }}
      
